"""Render the computational panels of manuscript Figures 4, 5, and 6.

The renderer uses compact numerical outputs bundled in ``source_data``. The
neural traces in Figure 4a and the correlation histogram in Figure 4b are
generated numerically. Motion icons and the method schematics in Figures 4c,
4i, 5a, and 5e are not generated by this script.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection
from matplotlib.colors import Normalize, hsv_to_rgb
from matplotlib.ticker import FuncFormatter, MaxNLocator
from matplotlib.transforms import Bbox
from mpl_toolkits.mplot3d.art3d import Line3DCollection
import numpy as np
from scipy import stats
from scipy.io import loadmat


REPO_ROOT = Path(__file__).resolve().parents[2]
MANIFOLD = REPO_ROOT / "source_data" / "manifold_topology"
REGIONAL = REPO_ROOT / "source_data" / "regional_topology"
OUT_MANIFOLD = REPO_ROOT / "outputs" / "manifold_topology" / "panels"
OUT_REGIONAL = REPO_ROOT / "outputs" / "regional_topology" / "panels"

W2 = np.asarray([0.0, 0.5, 1.0, 3.0])
MOTION_NAMES = {"rot": "T-Rot", "p8": "8DT", "zvert": "Vert"}
MOTION_COLORS = {"rot": "#8064C0", "p8": "#4A7EBB", "zvert": "#F5A24B"}
TRAJECTORY_MOTIONS = (
    ("p8", "8DT", "d", "j"),
    ("rot", "T-Rot", "e", "k"),
    ("tilt", "Roll", "f", "l"),
    ("zvert", "Vert", "g", "m"),
    ("yaw", "Yaw", "h", "n"),
)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def sem(values: np.ndarray, axis: int | None = None) -> np.ndarray:
    values = np.asarray(values, dtype=float)
    n = np.sum(np.isfinite(values), axis=axis)
    return np.nanstd(values, axis=axis, ddof=1) / np.sqrt(np.maximum(n, 1))


def bonferroni(values: list[float] | np.ndarray) -> np.ndarray:
    values = np.asarray(values, dtype=float)
    return np.minimum(1.0, values * values.size)


def stars(p_value: float) -> str:
    for threshold, label in ((1e-3, "***"), (1e-2, "**"), (5e-2, "*")):
        if p_value < threshold:
            return label
    return "n.s."


def ptext(p_value: float) -> str:
    for exponent in range(8, 2, -1):
        if p_value < 10.0 ** (-exponent):
            return rf"$p<10^{{-{exponent}}}$"
    return rf"$p={p_value:.3g}$"


def save_panel(fig: plt.Figure, directory: Path, stem: str) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    fig.savefig(directory / f"{stem}.svg", bbox_inches="tight", pad_inches=0.02)
    fig.savefig(directory / f"{stem}.png", bbox_inches="tight", pad_inches=0.02, dpi=300)
    plt.close(fig)


def render_figure_4ab() -> dict[str, object]:
    """Render the numerical content of the single-neuron panels."""

    source = MANIFOLD / "figure_04ab_plot_data.mat"
    data = loadmat(source, squeeze_me=True)
    colors = np.asarray(data["neuron_colors"], dtype=float)

    # Fig. 4a. The motion-platform icons are assembly artwork. This renderer
    # draws the two neural-activity plots from the bundled values.
    trot_mean = np.asarray(data["trot_mean"], dtype=float)
    trot_sem = np.asarray(data["trot_sem"], dtype=float)
    p8_mean = np.asarray(data["p8_mean"], dtype=float)
    p8_sem = np.asarray(data["p8_sem"], dtype=float)
    directions = np.asarray(data["p8_direction_degrees"], dtype=float)

    plt.rcParams.update({
        "font.family": "sans-serif", "font.sans-serif": ["Arial", "DejaVu Sans"],
        "font.size": 7, "axes.linewidth": 0.6, "svg.fonttype": "none",
        "figure.dpi": 200, "savefig.dpi": 300,
    })
    fig = plt.figure(figsize=(3.35, 2.25))
    top = fig.add_axes([0.14, 0.57, 0.75, 0.30])
    bottom = fig.add_axes([0.14, 0.10, 0.75, 0.34])
    for neuron in range(3):
        x = np.arange(trot_mean.shape[0])
        top.fill_between(
            x,
            trot_mean[:, neuron] - trot_sem[:, neuron],
            trot_mean[:, neuron] + trot_sem[:, neuron],
            color=colors[neuron],
            alpha=0.18,
            linewidth=0,
        )
        top.plot(x, trot_mean[:, neuron], color=colors[neuron], linewidth=1.05)

        n_time, n_direction = p8_mean.shape[:2]
        x_p8 = np.arange(n_time * n_direction)
        mean_flat = p8_mean[:, :, neuron].T.reshape(-1)
        sem_flat = p8_sem[:, :, neuron].T.reshape(-1)
        bottom.fill_between(
            x_p8,
            mean_flat - sem_flat,
            mean_flat + sem_flat,
            color=colors[neuron],
            alpha=0.15,
            linewidth=0,
        )
        bottom.plot(x_p8, mean_flat, color=colors[neuron], linewidth=0.62)

    for ax, label in ((top, "T-Rot"), (bottom, "8DT")):
        ax.set_axis_off()
        ax.text(-0.02, 0.88, label, transform=ax.transAxes, ha="right", va="top", fontsize=7)

    # Direction strip for the continuous rotation and arrows for the eight
    # discrete directions. The hues follow the manuscript's circular code.
    phase_angles = np.linspace(0, 360, trot_mean.shape[0])
    phase_hues = np.mod(0.75 - phase_angles / 360.0, 1.0)
    phase_rgb = hsv_to_rgb(
        np.column_stack((phase_hues, np.full_like(phase_hues, 0.92), np.ones_like(phase_hues)))
    )[None, :, :]
    phase_ax = fig.add_axes([0.14, 0.895, 0.75, 0.018])
    phase_ax.imshow(phase_rgb, aspect="auto", origin="lower", extent=[0, 360, 0, 1])
    phase_ax.set_axis_off()
    arrow_hues = np.mod(0.75 - directions / 360.0, 1.0)
    arrow_colors = hsv_to_rgb(
        np.column_stack((arrow_hues, np.full_like(arrow_hues, 0.92), np.ones_like(arrow_hues)))
    )
    centers = (np.arange(directions.size) + 0.5) * p8_mean.shape[0]
    for center, angle, color in zip(centers, directions, arrow_colors):
        radians = np.deg2rad(angle)
        delta_x = 11 * np.cos(radians)
        delta_y = -0.055 * np.sin(radians)
        bottom.annotate(
            "",
            xy=(center + delta_x, -0.15 + delta_y),
            xytext=(center - delta_x, -0.15 - delta_y),
            xycoords=(bottom.transData, bottom.transAxes),
            textcoords=(bottom.transData, bottom.transAxes),
            arrowprops={"arrowstyle": "-|>", "color": color, "lw": 0.8},
            clip_on=False,
        )

    def add_scale(ax: plt.Axes, seconds: float) -> None:
        y_low, y_high = ax.get_ylim()
        x_low, x_high = ax.get_xlim()
        x0 = x_high + 0.02 * (x_high - x_low)
        y0 = y_low + 0.12 * (y_high - y_low)
        ax.plot([x0, x0], [y0, y0 + 2], color="black", lw=0.7, clip_on=False)
        sample_count = seconds * 10
        ax.plot([x0, x0 + sample_count], [y0, y0], color="black", lw=0.7, clip_on=False)
        ax.text(x0 + 0.015 * (x_high - x_low), y0 + 1, "2 S.D.", va="center", fontsize=6)
        ax.text(x0 + sample_count / 2, y0 - 0.10 * (y_high - y_low), f"{seconds:g} s", ha="center", va="top", fontsize=6)

    add_scale(top, 0.5)
    add_scale(bottom, 3.0)
    fig.text(0.01, 0.99, "a", ha="left", va="top", fontsize=9, fontweight="bold")
    save_panel(fig, OUT_MANIFOLD, "figure_04a")

    # Fig. 4b. Use the MATLAB-generated bin edges and probability masses so
    # bin selection is identical to the source analysis.
    probabilities = np.asarray(data["hist_probability"], dtype=float)
    edges = np.asarray(data["hist_edges"], dtype=float)
    fig, ax = plt.subplots(figsize=(1.8, 1.65))
    ax.bar(
        edges[:-1], probabilities, width=np.diff(edges), align="edge",
        color="#4A4A4A", edgecolor="none",
    )
    ax.set_xlim(-1, 1)
    ax.set_ylim(bottom=0)
    ax.set_xticks([-1, 0, 1])
    ax.set_xlabel("Correlation between single-\nneuron responses to 8DT\nand T-Rot conditions", labelpad=1)
    ax.set_ylabel("Probability")
    ax.spines[["top", "right"]].set_visible(False)
    fig.text(0.01, 0.99, "b", ha="left", va="top", fontsize=9, fontweight="bold")
    fig.tight_layout(pad=0.55)
    save_panel(fig, OUT_MANIFOLD, "figure_04b")

    return {
        "source": str(source.relative_to(REPO_ROOT)).replace("\\", "/"),
        "sha256": sha256(source),
        "example_session_index": int(data["plane_index"]),
        "example_neuron_count": int(np.asarray(data["cell_indices"]).size),
        "p8_trials_per_direction": int(data["n_p8_trials"]),
        "trot_trials": int(data["n_trot_trials"]),
        "correlation_neuron_count": int(np.asarray(data["corr_all"]).size),
        "correlation_minimum": float(np.nanmin(data["corr_all"])),
        "correlation_maximum": float(np.nanmax(data["corr_all"])),
        "panels": 2,
    }


def jumping_mean(data: np.ndarray, axis: int, num_to_combine: int) -> np.ndarray:
    """Match the interleaved trial grouping used by the original helper."""

    data = np.asarray(data)
    step_size = int(np.round(data.shape[axis] / num_to_combine))
    means = []
    for start in range(step_size):
        indices = np.arange(start, data.shape[axis], step_size, dtype=int)
        means.append(np.take(data, indices, axis=axis).mean(axis=axis))
    return np.stack(means, axis=axis)


def circular_colors(values: np.ndarray) -> np.ndarray:
    indices = np.rint(255 * np.mod(values, 2 * np.pi) / (2 * np.pi)).astype(int)
    return plt.get_cmap("hsv")(np.linspace(0, 1, 256))[indices]


def scalar_colors(
    values: np.ndarray,
    minimum_maximum: tuple[float, float] | None = None,
    code_direction: bool = False,
) -> np.ndarray:
    values = np.asarray(values, dtype=float).copy()
    if minimum_maximum is None:
        low, high = float(np.nanmin(values)), float(np.nanmax(values))
    else:
        low, high = map(float, minimum_maximum)
    values = np.clip(values, low, high)
    scaled = (values - low) / (high - low)
    if code_direction:
        delta = np.diff(scaled, axis=1)
        delta = np.concatenate((delta, delta[:, -1:]), axis=1)
        scaled[delta < 0] *= -1
        scaled = (scaled + 1) / 2
    indices = np.rint(255 * scaled).astype(int)
    return plt.get_cmap("hsv")(np.linspace(0, 1, 256))[indices]


def trajectory_points(values: np.ndarray, field: str, n_trials: int) -> np.ndarray:
    axis = 1 if field == "p8" else 0
    averaged = jumping_mean(values, axis=axis, num_to_combine=n_trials)
    return averaged.reshape(-1, averaged.shape[-1])


def trajectory_segments(
    values: np.ndarray,
    stimulus: np.ndarray,
    field: str,
    n_trials: int,
) -> tuple[np.ndarray, np.ndarray]:
    if field == "p8":
        averaged = jumping_mean(values, axis=1, num_to_combine=n_trials)
        segments = np.stack(
            (averaged[:, :, :-1, :].reshape(-1, 3), averaged[:, :, 1:, :].reshape(-1, 3)),
            axis=1,
        )
        direction = jumping_mean(stimulus[:, :, :, 0], axis=1, num_to_combine=n_trials)
        modal = stats.mode(direction, axis=2, keepdims=True).mode
        direction = np.broadcast_to(modal, direction.shape)
        colors = circular_colors(direction[:, :, :-1]).reshape(-1, 4)
        return segments, colors

    averaged = jumping_mean(values, axis=0, num_to_combine=n_trials)
    segments = np.stack(
        (averaged[:, :-1, :].reshape(-1, 3), averaged[:, 1:, :].reshape(-1, 3)),
        axis=1,
    )
    if field == "rot":
        colors = circular_colors(stimulus[:, 1:, 0])
        colors = jumping_mean(colors, axis=0, num_to_combine=n_trials).reshape(-1, 4)
    else:
        parameter_index = {"tilt": 0, "zvert": 5, "yaw": 2}[field]
        parameter = jumping_mean(
            stimulus[:, 1:, parameter_index], axis=0, num_to_combine=n_trials
        )
        colors = scalar_colors(
            parameter,
            minimum_maximum=(0, 2 * np.pi) if field == "tilt" else None,
            code_direction=field in ("zvert", "yaw"),
        ).reshape(-1, 4)
    return segments, colors


def limits_and_ticks(points: np.ndarray) -> list[tuple[float, float, np.ndarray]]:
    points = np.asarray(points, dtype=float)
    spans = [
        max(float(np.nanmax(points[:, dim]) - np.nanmin(points[:, dim])), 1.0)
        for dim in range(3)
    ]
    common = max(spans)
    output = []
    for dim in range(3):
        midpoint = 0.5 * (float(np.nanmin(points[:, dim])) + float(np.nanmax(points[:, dim])))
        low = midpoint - 0.5 * common
        high = midpoint + 0.5 * common
        pad = 0.02 * common
        axis_low, axis_high = low - pad, high + pad
        locator = MaxNLocator(nbins=6, steps=[1, 2, 2.5, 5, 10])
        ticks = np.asarray(locator.tick_values(axis_low, axis_high), dtype=float)
        ticks = ticks[(ticks >= axis_low) & (ticks <= axis_high)]
        if ticks.size < 2:
            ticks = np.asarray([axis_low, axis_high])
        output.append((axis_low, axis_high, ticks))
    return output


def endpoint_zero_formatter(ticks: np.ndarray) -> FuncFormatter:
    ticks = np.asarray(ticks, dtype=float)

    def format_tick(value: float, _position: int) -> str:
        keep = np.isclose(value, ticks[0]) or np.isclose(value, ticks[-1])
        if np.any(np.isclose(ticks, 0.0)):
            keep = keep or np.isclose(value, 0.0)
        return f"{value:g}" if keep else ""

    return FuncFormatter(format_tick)


def depth_sort_callback(ax: plt.Axes, segments: np.ndarray, colors: np.ndarray, collection: Line3DCollection):
    def callback(event) -> None:
        if event.canvas.figure is not ax.figure:
            return
        from mpl_toolkits.mplot3d import proj3d

        midpoints = segments.mean(axis=1)
        _, _, z_values = proj3d.proj_transform(
            midpoints[:, 0], midpoints[:, 1], midpoints[:, 2], ax.get_proj()
        )
        order = np.argsort(z_values)[::-1]
        collection.set_segments(segments[order])
        collection.set_color(colors[order])

    return callback


def draw_3d_trajectory(
    ax: plt.Axes,
    values: np.ndarray,
    stimulus: np.ndarray,
    field: str,
    n_trials: int,
    linewidth: float = 1.05,
) -> None:
    segments, colors = trajectory_segments(values, stimulus, field, n_trials)
    collection = Line3DCollection(segments, linewidths=linewidth, alpha=1, colors=colors)
    try:
        ax.add_collection3d(collection, autolim=False)
    except TypeError:
        # Matplotlib before 3.8 has no ``autolim`` argument. Every caller sets
        # explicit 3-D limits immediately afterwards, so both branches are
        # numerically and visually equivalent.
        ax.add_collection3d(collection)
    ax.figure.canvas.mpl_connect(
        "draw_event", depth_sort_callback(ax, segments, colors, collection)
    )


def style_3d_axis(
    ax: plt.Axes,
    title: str,
    panel_letter: str,
    limits: list[tuple[float, float, np.ndarray]],
) -> None:
    for setter, (low, high, ticks) in zip(
        (ax.set_xlim3d, ax.set_ylim3d, ax.set_zlim3d), limits
    ):
        setter(low, high)
    ax.set_xticks(limits[0][2])
    ax.set_yticks(limits[1][2])
    ax.set_zticks(limits[2][2])
    ax.xaxis.set_major_formatter(endpoint_zero_formatter(limits[0][2]))
    ax.yaxis.set_major_formatter(endpoint_zero_formatter(limits[1][2]))
    ax.zaxis.set_major_formatter(endpoint_zero_formatter(limits[2][2]))
    ax.set_xlabel("PC1", labelpad=-8)
    ax.set_ylabel("PC2", labelpad=0)
    ax.set_zlabel("PC3", labelpad=0)
    ax.tick_params(axis="x", pad=0, length=2, width=0.5)
    ax.tick_params(axis="y", pad=5, length=2, width=0.5)
    ax.tick_params(axis="z", pad=2, length=2, width=0.5)
    ax.view_init(elev=10, azim=80, roll=0)
    ax.set_box_aspect((1, 1, 1))
    ax.set_title(title, pad=1.5, fontweight="normal")
    ax.text2D(
        0.01, 0.99, panel_letter, transform=ax.transAxes,
        ha="left", va="top", fontsize=11, fontweight="bold"
    )
    for axis in (ax.xaxis, ax.yaxis, ax.zaxis):
        axis._axinfo["grid"].update(
            {"linewidth": 0.45, "linestyle": "-", "color": (0.68, 0.68, 0.68, 1)}
        )
        axis._axinfo["axisline"].update({"linewidth": 0.65, "color": (0, 0, 0, 1)})
        axis.pane.set_facecolor((1, 1, 1, 1))
        axis.pane.set_edgecolor((0.7, 0.7, 0.7, 1))


def render_figure_4_trajectories() -> dict[str, object]:
    source = MANIFOLD / "figure_04d_n_plot_data.npz"
    data = np.load(source)
    n_trials = int(data["trial_average_count"])
    pair_limits = {}
    for field, _title, _letter_c, _letter_g in TRAJECTORY_MOTIONS:
        points = np.concatenate(
            [
                trajectory_points(data[f"cpca_{field}"], field, n_trials),
                trajectory_points(data[f"gcpca_{field}"], field, n_trials),
            ],
            axis=0,
        )
        pair_limits[field] = limits_and_ticks(points)

    plt.rcParams.update({
        "font.family": "sans-serif", "font.sans-serif": ["Arial", "DejaVu Sans"],
        "font.size": 8, "axes.titlesize": 9, "axes.labelsize": 8,
        "xtick.labelsize": 7, "ytick.labelsize": 7, "axes.linewidth": 0.65,
        "svg.fonttype": "none", "figure.dpi": 180, "savefig.dpi": 300,
    })
    for prefix, row_label, letter_index in (("cpca", "cPCA", 2), ("gcpca", "gcPCA", 3)):
        for column, (field, title, letter_c, letter_g) in enumerate(TRAJECTORY_MOTIONS):
            letter = (letter_c, letter_g)[letter_index - 2]
            fig = plt.figure(figsize=(3.65, 3.45))
            ax = fig.add_subplot(111, projection="3d")
            draw_3d_trajectory(
                ax, data[f"{prefix}_{field}"], data[f"stimulus_{field}"], field, n_trials
            )
            style_3d_axis(ax, title, letter, pair_limits[field])
            if column == 0:
                fig.text(0.015, 0.52, row_label, ha="left", va="center", fontsize=11, fontstyle="italic")
            fig.subplots_adjust(left=0.16, right=0.93, bottom=0.16, top=0.91)
            save_panel(fig, OUT_MANIFOLD, f"figure_04{letter}")
    return {
        "source": str(source.relative_to(REPO_ROOT)).replace("\\", "/"),
        "sha256": sha256(source),
        "plane_index": int(data["plane_index"]),
        "active_neuron_count": int(data["n_active"]),
        "panels": 10,
    }


def draw_motion_key(ax: plt.Axes, field: str, label: str) -> None:
    ax.set_xlim(-1.25, 1.25)
    ax.set_ylim(-1.35, 1.35)
    ax.set_aspect("equal")
    ax.axis("off")
    if field in ("rot", "p8"):
        angle = np.linspace(0, 2 * np.pi, 80, endpoint=False)
        ax.scatter(
            np.cos(angle), np.sin(angle), c=plt.get_cmap("hsv")(angle / (2 * np.pi)),
            s=7, linewidths=0,
        )
        if field == "rot":
            for start in (0.35 * np.pi, 1.35 * np.pi):
                ax.annotate(
                    "", xy=(0.78 * np.cos(start + 0.55), 0.78 * np.sin(start + 0.55)),
                    xytext=(0.78 * np.cos(start), 0.78 * np.sin(start)),
                    arrowprops=dict(arrowstyle="->", color="k", lw=0.65, connectionstyle="arc3,rad=0.22"),
                )
        else:
            for start in np.linspace(0, 2 * np.pi, 8, endpoint=False):
                ax.annotate(
                    "", xy=(0.83 * np.cos(start), 0.83 * np.sin(start)), xytext=(0, 0),
                    arrowprops=dict(arrowstyle="->", color="k", lw=0.55),
                )
        ax.text(0, -1.28, label, ha="center", va="top", fontsize=7.5)
    else:
        ax.text(0, 0, label, ha="center", va="center", fontsize=7.5)


def draw_scale_bar(ax: plt.Axes, half_range: float, bar_length: float) -> None:
    padding = 0.08 * bar_length
    ax.set_xlim(0, bar_length + 2 * padding)
    ax.set_ylim(-half_range, half_range)
    ax.set_aspect("equal", adjustable="box")
    ax.set_anchor("W")
    ax.axis("off")
    x0, x1 = padding, padding + bar_length
    y0 = -0.73 * half_range
    ax.plot([x0, x0, x1], [y0 + bar_length, y0, y0], color="k", lw=0.85, clip_on=False)
    ax.text((x0 + x1) / 2, y0 - 0.09 * half_range, f"{bar_length:g} S.D.", ha="center", va="top", fontsize=6.5)


def render_figure_4o() -> dict[str, object]:
    source = MANIFOLD / "figure_04o_plot_data.npz"
    data = np.load(source)
    motions = [str(value) for value in data["motions"]]
    labels = [str(value) for value in data["motion_labels"]]
    half_ranges = np.asarray(data["row_half_ranges"], dtype=float)
    bar_length = float(data["fixed_scale_bar_sd"])

    plt.rcParams.update({
        "font.family": "sans-serif", "font.sans-serif": ["Arial", "DejaVu Sans"],
        "font.size": 7, "axes.titlesize": 8, "svg.fonttype": "none",
        "figure.dpi": 200, "savefig.dpi": 300,
    })
    fig = plt.figure(figsize=(6.8, 2.85))
    grid = fig.add_gridspec(
        3, 6, width_ratios=(0.58, 1, 1, 1, 1, 0.42),
        left=0.015, right=0.995, top=0.90, bottom=0.025, wspace=0.16, hspace=0.18,
    )
    for row, (field, label, half_range) in enumerate(zip(motions, labels, half_ranges)):
        draw_motion_key(fig.add_subplot(grid[row, 0]), field, label)
        for weight_index, weight in enumerate(np.asarray(data["w2"], dtype=float)):
            ax = fig.add_subplot(grid[row, weight_index + 1])
            cloud = np.asarray(data[f"{field}_cloud_{weight_index}"], dtype=float)
            colors = np.asarray(data[f"{field}_colors_{weight_index}"])
            ellipse = np.asarray(data[f"{field}_ellipse_{weight_index}"], dtype=float)
            center = cloud.mean(axis=0)
            cloud = cloud - center
            ellipse = ellipse - center
            ax.plot(ellipse[:, 0], ellipse[:, 1], color="k", lw=0.8, zorder=2)
            ax.scatter(
                cloud[:, 0], cloud[:, 1], c=colors, s=7.5 if field != "zvert" else 5,
                edgecolors="none", zorder=3,
            )
            ax.set_xlim(-half_range, half_range)
            ax.set_ylim(-half_range, half_range)
            ax.set_aspect("equal")
            ax.set_xticks([])
            ax.set_yticks([])
            for spine in ax.spines.values():
                spine.set_visible(False)
            if row == 0:
                ax.set_title(rf"$w_2$ = {weight:g}", pad=3)
        draw_scale_bar(fig.add_subplot(grid[row, 5]), float(half_range), bar_length)
    save_panel(fig, OUT_MANIFOLD, "figure_04o")
    return {
        "source": str(source.relative_to(REPO_ROOT)).replace("\\", "/"),
        "sha256": sha256(source),
        "plane_index": int(data["plane_index"]),
        "fixed_scale_bar_sd": bar_length,
        "panels": 1,
    }


def band(ax: plt.Axes, x: np.ndarray, values: np.ndarray, color: str, label: str | None = None):
    mean = np.nanmean(values, axis=1)
    error = sem(values, axis=1)
    ax.plot(x, mean, "-", lw=1.4, color=color, label=label)
    ax.fill_between(x, mean - error, mean + error, color=color, alpha=0.30, lw=0)
    return mean, error


def log_slopes(values: np.ndarray) -> np.ndarray:
    output = np.full(values.shape[1], np.nan)
    for column in range(values.shape[1]):
        response = np.log(values[:, column] + 1e-300)
        valid = np.isfinite(response)
        if valid.sum() > 2:
            output[column] = np.polyfit(W2[valid], response[valid], 1)[0]
    return output


def load_ellipse_values() -> tuple[np.ndarray, list[str]]:
    loaded = [np.load(MANIFOLD / f"skewfilter_plane{index:02d}.npz", allow_pickle=True) for index in range(20)]
    sets = [str(value) for value in loaded[0]["sets"]]
    motions = [str(value) for value in loaded[0]["motions"]]
    values = np.stack([entry["ell"] for entry in loaded])[:, sets.index("active")]
    return values, motions


def render_figure_4pq() -> dict[str, object]:
    ellipse, motions = load_ellipse_values()
    session_count = ellipse.shape[0]

    normalized = {
        motion: (
            ellipse[:, :, motions.index(motion), 0].T
            / ellipse[:, 0:1, motions.index(motion), 0].T
        )
        for motion in MOTION_NAMES
    }
    raw_p = [
        stats.wilcoxon(normalized[motion][index], np.ones(session_count), alternative="less").pvalue
        for motion in MOTION_NAMES for index in range(1, len(W2))
    ]
    adjusted = bonferroni(raw_p)
    slopes = {
        motion: log_slopes(ellipse[:, :, motions.index(motion), 0].T)
        for motion in MOTION_NAMES
    }
    slope_adjusted = bonferroni([
        stats.wilcoxon(slopes["zvert"], slopes[motion], alternative="less").pvalue
        for motion in ("rot", "p8")
    ])

    plt.rcParams.update({
        "font.family": "sans-serif", "font.sans-serif": ["Arial", "DejaVu Sans"],
        "font.size": 7, "axes.labelsize": 7.5, "axes.titlesize": 7.5,
        "xtick.labelsize": 7, "ytick.labelsize": 7, "legend.fontsize": 6.5,
        "axes.linewidth": 0.7, "axes.spines.top": False, "axes.spines.right": False,
        "xtick.major.width": 0.7, "ytick.major.width": 0.7,
        "svg.fonttype": "none", "figure.dpi": 200,
    })
    fig, ax = plt.subplots(figsize=(2.35, 1.95))
    for motion in ("rot", "p8", "zvert"):
        band(ax, W2, normalized[motion], MOTION_COLORS[motion], MOTION_NAMES[motion])
    ax.set_ylim(-0.03, 1.30)
    ax.plot([0.45, 3.0], [1.16, 1.16], "-", color="k", lw=0.9)
    ax.text(1.72, 1.19, ptext(float(adjusted.max())), ha="center", fontsize=6.8)
    for index, (x_position, low, high) in enumerate(((3.30, 0.03, 0.83), (3.80, 0.03, 0.68))):
        ax.plot([x_position, x_position], [low, high], "-", color="k", lw=0.9, clip_on=False)
        ax.text(x_position + 0.10, (low + high) / 2, stars(float(slope_adjusted[index])), va="center", ha="left", fontsize=7.5, clip_on=False)
    ax.set_xticks(W2)
    ax.set_xlabel(r"$w_2$")
    ax.set_ylabel("Normalized elliptical area")
    ax.legend(frameon=False, loc="center left", bbox_to_anchor=(1.55, 0.82))
    save_panel(fig, OUT_MANIFOLD, "figure_04p")

    raw = []
    keys = []
    for motion in ("rot", "p8"):
        values = ellipse[:, :, motions.index(motion), 1].T
        for index in range(1, len(W2)):
            raw.append(stats.wilcoxon(values[index], values[0], alternative="less").pvalue)
            keys.append((motion, index))
    adjusted_map = dict(zip(keys, bonferroni(raw)))
    fig, axes = plt.subplots(1, 2, figsize=(3.9, 1.95))
    for ax, motion in zip(axes, ("rot", "p8")):
        values = ellipse[:, :, motions.index(motion), 1].T
        band(ax, W2, values, MOTION_COLORS[motion])
        p_values = np.asarray([adjusted_map[(motion, index)] for index in range(1, len(W2))])
        low, high = ax.get_ylim()
        ax.set_ylim(low, high + 0.30 * (high - low))
        low, high = ax.get_ylim()
        ax.plot([0.45, 3.0], [high - 0.14 * (high - low)] * 2, "-", color="k", lw=0.9)
        ax.text(1.72, high - 0.11 * (high - low), ptext(float(p_values.max())), ha="center", fontsize=6.8)
        ax.text(2.95, low + 0.06 * (high - low), MOTION_NAMES[motion], ha="right", fontsize=7.5, color=MOTION_COLORS[motion])
        ax.set_xticks(W2)
        ax.set_xlabel(r"$w_2$")
    axes[0].set_ylabel("Axis ratio")
    fig.tight_layout(w_pad=1.4)
    save_panel(fig, OUT_MANIFOLD, "figure_04q")
    return {
        "session_count": session_count,
        "source_files": 20,
        "figure_4p_largest_adjusted_p": float(adjusted.max()),
        "figure_4q_largest_adjusted_p_by_motion": {
            motion: float(max(adjusted_map[(motion, index)] for index in range(1, len(W2))))
            for motion in ("rot", "p8")
        },
        "panels": 2,
    }


def plot_h1_barcodes(ax: plt.Axes, diagram: np.ndarray, color: str) -> None:
    diagram = np.asarray(diagram, dtype=float)
    order = np.argsort(diagram[:, 0])
    diagram = diagram[order]
    y_positions = np.arange(diagram.shape[0])
    segments = np.stack(
        (
            np.column_stack((diagram[:, 0], y_positions)),
            np.column_stack((diagram[:, 1], y_positions)),
        ),
        axis=1,
    )
    ax.add_collection(LineCollection(segments, colors=color, linewidths=0.55))
    ax.set_ylim(-1, diagram.shape[0] + 1)
    ax.set_yticks([])
    ax.grid(axis="x", linestyle=":", color="0.85")


def render_figure_5bc() -> dict[str, object]:
    source = MANIFOLD / "figure_05bc_plot_data.npz"
    data = np.load(source)
    weights = np.asarray(data["w2"], dtype=float)
    plt.rcParams.update({
        "font.family": "sans-serif", "font.sans-serif": ["Arial", "DejaVu Sans"],
        "font.size": 7, "axes.labelsize": 7.5, "axes.titlesize": 7.5,
        "xtick.labelsize": 6.5, "ytick.labelsize": 6.5,
        "axes.linewidth": 0.7, "axes.spines.top": True,
        "axes.spines.right": True, "svg.fonttype": "none", "figure.dpi": 200,
    })
    maxima = {}
    for field, label, stem, color in (
        ("rot", "T-Rot", "figure_05b", "#7E57C2"),
        ("zvert", "Vert", "figure_05c", "#F5A623"),
    ):
        diagrams = [np.asarray(data[f"h1_{field}_{index}"], dtype=float) for index in range(4)]
        maximum = max(float(np.nanmax(diagram[:, 1])) for diagram in diagrams) * 1.05
        maxima[field] = maximum
        fig, axes = plt.subplots(1, 4, figsize=(5.6, 1.6), constrained_layout=True, sharex=True)
        for index, (ax, weight, diagram) in enumerate(zip(axes, weights, diagrams)):
            plot_h1_barcodes(ax, diagram, color)
            ax.set_xlim(0, maximum)
            ax.set_xlabel("Filtration")
            ax.set_title(rf"$w_2$ = {weight:g}", fontsize=7)
            if index == 0:
                ax.set_ylabel(label, fontsize=7.5)
        save_panel(fig, OUT_MANIFOLD, stem)
    return {
        "source": str(source.relative_to(REPO_ROOT)).replace("\\", "/"),
        "sha256": sha256(source),
        "plane_index": int(data["plane"]),
        "active_neuron_count": int(data["n_active"]),
        "filtration_maxima": maxima,
        "panels": 2,
    }


def load_figure_5_values() -> tuple[np.ndarray, np.ndarray, list[str]]:
    loaded = [
        np.load(MANIFOLD / f"plane{index:02d}_manifold.npz", allow_pickle=True)
        for index in range(20)
    ]
    subsets = [str(value) for value in loaded[0]["subsets"]]
    metrics = [str(value) for value in loaded[0]["metrics"]]
    motions = [str(value) for value in loaded[0]["motions"]]
    conditions = [str(value) for value in loaded[0]["cond_A_is"]]
    active_index = subsets.index("active")
    weight_indices = [conditions.index(f"{weight:.1f}") for weight in W2]
    arrays = np.stack([entry["A_is"] for entry in loaded])
    maxlife = arrays[:, active_index, :, :, metrics.index("maxlife")]
    lri = arrays[:, active_index, :, :, metrics.index("lri")]
    maxlife = maxlife[:, weight_indices, :]
    lri = lri[:, weight_indices, :]
    maxlife = maxlife / maxlife[:, 0:1, :]
    # Public plotting order is weight, motion, session.
    return maxlife.transpose(1, 2, 0), lri.transpose(1, 2, 0), motions


def render_figure_5df() -> dict[str, object]:
    maxlife, lri, motions = load_figure_5_values()
    session_count = maxlife.shape[2]
    results = {}
    for stem, values, y_label, levels, use_log in (
        ("figure_05d", maxlife, "Normalized max H1 lifetime", range(1, 4), True),
        ("figure_05f", lri, "Persistent landscape\nringness index", range(4), False),
    ):
        raw = []
        keys = []
        for motion in ("rot", "p8"):
            for index in levels:
                first = values[index, motions.index(motion)]
                second = values[index, motions.index("zvert")]
                if use_log:
                    first, second = np.log(first), np.log(second)
                raw.append(stats.wilcoxon(first, second, alternative="greater").pvalue)
                keys.append((motion, index))
        adjusted = dict(zip(keys, bonferroni(raw)))

        fig, ax = plt.subplots(figsize=(2.35, 1.95))
        for motion in ("rot", "p8", "zvert"):
            band(ax, W2, values[:, motions.index(motion)], MOTION_COLORS[motion], MOTION_NAMES[motion])
        low, high = ax.get_ylim()
        ax.set_ylim(low, high + 0.18 * (high - low))
        low, high = ax.get_ylim()
        for row, motion in enumerate(("rot", "p8")):
            for index in levels:
                label = stars(float(adjusted[(motion, index)]))
                if label != "n.s.":
                    ax.text(W2[index], high - (0.04 + 0.065 * row) * (high - low), label, ha="center", va="center", fontsize=7, color=MOTION_COLORS[motion])
        ax.set_xticks(W2)
        ax.set_xlabel(r"$w_2$")
        ax.set_ylabel(y_label)
        ax.legend(frameon=False, loc="center left", bbox_to_anchor=(1.02, 0.5))
        save_panel(fig, OUT_MANIFOLD, stem)
        results[stem] = {
            f"{motion}_{W2[index]:g}": float(adjusted[(motion, index)])
            for motion in ("rot", "p8") for index in levels
        }
    return {"session_count": session_count, "adjusted_p_values": results, "panels": 2}


def equal_limits_regional(points: np.ndarray) -> list[tuple[float, float, np.ndarray]]:
    points = np.asarray(points, dtype=float)
    spans = [max(float(np.ptp(points[:, dim])), 1.0) for dim in range(3)]
    common = max(spans) * 1.04
    locator = MaxNLocator(nbins=4, steps=[1, 2, 2.5, 5, 10])
    output = []
    for dim in range(3):
        midpoint = 0.5 * (float(np.min(points[:, dim])) + float(np.max(points[:, dim])))
        low, high = midpoint - 0.5 * common, midpoint + 0.5 * common
        ticks = np.asarray(locator.tick_values(low, high), dtype=float)
        ticks = ticks[(ticks >= low) & (ticks <= high)]
        if ticks.size < 2:
            ticks = np.asarray([low, high])
        output.append((low, high, ticks))
    return output


def plane_aligned_view(points: np.ndarray) -> tuple[float, float, float]:
    centered = points - points.mean(axis=0, keepdims=True)
    _, eigenvectors = np.linalg.eigh(np.cov(centered, rowvar=False))
    normal = eigenvectors[:, 0]
    if normal[2] < 0:
        normal = -normal
    elevation = float(np.degrees(np.arcsin(np.clip(normal[2], -1, 1))))
    azimuth = float(np.degrees(np.arctan2(normal[1], normal[0])) % 360)
    return elevation, azimuth, 0.0


def style_figure_6a_grid(ax: plt.Axes, target_divisor: float = 12.0) -> None:
    """Match the refined Figure 6a grid without changing the saved view."""

    ax.patch.set_visible(False)
    limits = np.asarray([ax.get_xlim3d(), ax.get_ylim3d(), ax.get_zlim3d()], dtype=float)
    span = float(np.max(np.abs(np.diff(limits, axis=1))))
    target = span / target_divisor
    power = 10.0 ** np.floor(np.log10(target))
    choices = power * np.asarray([1.0, 2.0, 2.5, 5.0, 10.0])
    step = float(choices[np.argmin(np.abs(np.log(choices / target)))])
    for pc, (axis, (low, high)) in enumerate(
        zip((ax.xaxis, ax.yaxis, ax.zaxis), limits), start=1
    ):
        ticks = step * np.arange(np.ceil(low / step), np.floor(high / step) + 1)
        ticks[np.isclose(ticks, 0.0)] = 0.0
        labelled = {0, len(ticks) - 1, int(np.argmin(np.abs(ticks)))}
        axis.set_ticks(ticks)
        axis.set_ticklabels([f"{value:g}" if index in labelled else "" for index, value in enumerate(ticks)])
        axis.pane.set_facecolor("white")
        axis.pane.set_edgecolor("none")
        axis.pane.set_linewidth(0.0)
        axis.pane.set_alpha(1.0)
        axis._axinfo["grid"].update(color="0.65", linewidth=0.30, linestyle="-")
        axis.set_label_text(f"PC{pc}", fontsize=6.5)
        axis.labelpad = -2.0
    ax.set_xlim3d(*limits[0])
    ax.set_ylim3d(*limits[1])
    ax.set_zlim3d(*limits[2])


def render_figure_6a() -> dict[str, object]:
    source = REGIONAL / "fig6a_active_m1m2_projection_cache.npz"
    view_source = REGIONAL / "fig6a_manual_view_state.npz"
    data = np.load(source, allow_pickle=False)
    view = np.load(view_source, allow_pickle=False)
    n_trials = int(data["ntri"])
    groups = (("PPC", "PPC"), ("S1", "S1"), ("M1M2", "M1 + M2"))
    motions = (("p8", "8DT"), ("rot", "T-Rot"), ("tilt", "Roll"))
    row_views = np.asarray(view["row_views"], dtype=float)
    saved_limits = np.asarray(view["limits"], dtype=float)
    s1_pc3_positions = np.asarray(view["s1_pc3_positions"], dtype=float)
    if int(data["plane"]) != 17 or int(view["plane"]) != 17:
        raise ValueError("Figure 6a must use zero-based plane 17")
    if (
        row_views.shape != (3, 3)
        or saved_limits.shape != (9, 3, 2)
        or s1_pc3_positions.shape != (3, 2)
    ):
        raise ValueError("Figure 6a view state has an unexpected shape")
    plt.rcParams.update({
        "font.family": "sans-serif", "font.sans-serif": ["Arial", "DejaVu Sans"],
        "font.size": 8, "axes.titlesize": 8.5, "axes.labelsize": 7.5,
        "xtick.labelsize": 6.5, "ytick.labelsize": 6.5, "axes.linewidth": 0.65,
        "svg.fonttype": "none", "figure.dpi": 180, "savefig.dpi": 300,
    })
    fig = plt.figure(figsize=(5.6, 5.8))
    fig.subplots_adjust(left=0.085, right=0.99, top=0.92, bottom=0.02, wspace=0.02, hspace=0.06)
    axes = {}
    for row, (group, label) in enumerate(groups):
        for column, (field, motion_label) in enumerate(motions):
            ax = fig.add_subplot(3, 3, row * 3 + column + 1, projection="3d")
            axes[(row, column)] = ax
            draw_3d_trajectory(ax, data[f"{group}_{field}"], data[f"ktp_{field}"], field, n_trials, linewidth=0.7)
            panel_limits = saved_limits[row * 3 + column]
            ax.set_xlim3d(*panel_limits[0])
            ax.set_ylim3d(*panel_limits[1])
            ax.set_zlim3d(*panel_limits[2])
            ax.view_init(elev=row_views[row, 0], azim=row_views[row, 1], roll=row_views[row, 2])
            ax.set_box_aspect((1, 1, 1))
            ax.tick_params(pad=-1.5, length=2)
            style_figure_6a_grid(ax)
            if row == 1:
                ax.set_zlabel("")
            if row == 0:
                ax.set_title(motion_label, pad=1)
    for x_position, y_position in s1_pc3_positions:
        fig.text(
            x_position,
            y_position,
            "PC3",
            fontsize=6.5,
            ha="center",
            va="bottom",
        )
    for row, (group, label) in enumerate(groups):
        position = axes[(row, 0)].get_position()
        fig.text(
            0.012,
            position.y0 + position.height / 2,
            f"{label}\n(n = {int(data[f'{group}_n_active'])} active)",
            rotation=90,
            va="center",
            ha="left",
            fontsize=7.5,
        )
    fig.text(0.006, 0.988, "a", ha="left", va="top", fontsize=9, fontweight="bold")
    OUT_REGIONAL.mkdir(parents=True, exist_ok=True)
    width, height = fig.get_size_inches()
    export_box = Bbox.from_bounds(0.0, -0.12, width + 0.25, height + 0.12)
    for extension in ("svg", "png"):
        fig.savefig(
            OUT_REGIONAL / f"figure_06a.{extension}",
            dpi=300,
            bbox_inches=export_box,
            pad_inches=0,
        )
    plt.close(fig)
    return {
        "source": str(source.relative_to(REPO_ROOT)).replace("\\", "/"),
        "sha256": sha256(source),
        "view_source": str(view_source.relative_to(REPO_ROOT)).replace("\\", "/"),
        "view_sha256": sha256(view_source),
        "plane_index": int(data["plane"]),
        "active_neuron_counts": {group: int(data[f"{group}_n_active"]) for group, _ in groups},
        "saved_camera_and_axis_state_used": True,
        "panels": 1,
    }


def render_figure_6b() -> dict[str, object]:
    loaded = [np.load(REGIONAL / f"fig6b_m1m2_plane{index:02d}.npz", allow_pickle=True) for index in range(20)]
    regions = [str(value) for value in loaded[0]["regions"]]
    labels = {"AllAreas": "All areas", "PPC": "PPC", "S1": "S1", "M1M2": "M1 + M2"}
    lri = np.stack([entry["lri"] for entry in loaded])
    delta = lri[:, :, 0] - lri[:, :, 1]
    adjusted = bonferroni([
        stats.wilcoxon(delta[np.isfinite(delta[:, index]), index], alternative="greater").pvalue
        for index in range(len(regions))
    ])
    plt.rcParams.update({
        "font.family": "sans-serif", "font.sans-serif": ["Arial", "DejaVu Sans"],
        "font.size": 7, "axes.labelsize": 7.5, "xtick.labelsize": 6.5,
        "ytick.labelsize": 6.5, "axes.linewidth": 0.6,
        "axes.spines.top": False, "axes.spines.right": False,
        "svg.fonttype": "none", "figure.dpi": 180, "savefig.dpi": 300,
    })
    fig, ax = plt.subplots(figsize=(2.55, 2.15))
    x = np.arange(len(regions))
    for session in range(delta.shape[0]):
        ax.plot(x, delta[session], "-", color="0.735", linewidth=0.5)
    means = np.nanmean(delta, axis=0)
    errors = sem(delta, axis=0)
    ax.errorbar(x, means, yerr=errors, fmt="o-", color="black", markersize=3, linewidth=1.3, capsize=2, zorder=5)
    ax.axhline(0, color="0.35", linewidth=0.7)
    low, high = ax.get_ylim()
    ax.set_ylim(low, high + 0.12 * (high - low))
    low, high = ax.get_ylim()
    for index, p_value in enumerate(adjusted):
        label = stars(float(p_value))
        if label != "n.s.":
            ax.text(index, high - 0.055 * (high - low), label, ha="center", fontsize=7.5)
    ax.set_xticks(x)
    ax.set_xticklabels([labels[region] for region in regions], rotation=30, ha="right", rotation_mode="anchor")
    ax.set_ylabel(r"gcPCA LRI $-$ standard-PCA LRI")
    fig.text(0.005, 0.995, "b", ha="left", va="top", fontsize=9, fontweight="bold")
    fig.tight_layout(pad=0.7)
    save_panel(fig, OUT_REGIONAL, "figure_06b")
    return {
        "session_count": delta.shape[0],
        "means": dict(zip(regions, map(float, means))),
        "sem": dict(zip(regions, map(float, errors))),
        "adjusted_p_values": dict(zip(regions, map(float, adjusted))),
        "panels": 1,
    }


def render_figure_6c() -> dict[str, object]:
    loaded = [np.load(MANIFOLD / f"fig6c100_plane{index:02d}.npz", allow_pickle=True) for index in range(20)]
    arms = [str(value) for value in loaded[0]["arms"]]
    component_counts = [int(value) for value in loaded[0]["kk"]]
    values = np.stack([entry["R"] for entry in loaded])
    active_index = arms.index("active")
    x = np.arange(1, 11)
    fig, axes = plt.subplots(2, 1, figsize=(2.6, 3.5), sharex=True)
    result = {}
    for index, component_count in enumerate(component_counts):
        current = values[:, active_index, index, :].T
        baseline = np.median(current, axis=0)
        adjusted = bonferroni([
            stats.wilcoxon(current[dimension] - baseline, alternative="greater").pvalue
            for dimension in range(current.shape[0])
        ])
        mean = np.nanmean(current, axis=1)
        error = sem(current, axis=1)
        ax = axes[index]
        ax.errorbar(x, mean, yerr=error, fmt="o-", color="k", ms=2.8, lw=1.1, capsize=1.8)
        ax.set_ylim(0, float(max(mean + error)) * 1.28)
        for dimension in range(current.shape[0]):
            label = stars(float(adjusted[dimension]))
            if label != "n.s.":
                ax.text(x[dimension], mean[dimension] + error[dimension] + 0.035 * ax.get_ylim()[1], label, ha="center", fontsize=7.5)
        ax.set_xticks(x)
        ordinal = "3rd" if component_count == 3 else "5th"
        ax.set_ylabel(f"GCCA overlap with gcPCA\nsubspace (1st $-$ {ordinal})")
        result[str(component_count)] = {
            "mean": mean.tolist(), "sem": error.tolist(), "adjusted_p": adjusted.tolist()
        }
    axes[-1].set_xlabel("GCCA dimension")
    fig.tight_layout(h_pad=0.8)
    save_panel(fig, OUT_REGIONAL, "figure_06c")
    return {"regional_pca_components": 100, "session_count": values.shape[0], "results": result, "panels": 1}


def main() -> int:
    render_figure_4ab()
    render_figure_4_trajectories()
    render_figure_4o()
    render_figure_4pq()
    render_figure_5bc()
    render_figure_5df()
    render_figure_6a()
    render_figure_6b()
    render_figure_6c()
    print(f"Wrote Figures 4-6 panels to {OUT_MANIFOLD} and {OUT_REGIONAL}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
